- name: Install the required things
  hosts: all

  # vars:
  #   ansible_user: azureuser
  #   ansible_password: 'P@ssw0rdUseVaultorVarPrompt'
  #   ansible_connection: winrm
  #   ansible_port: 5986
  #   ansible_winrm_transport: ntlm
  #   ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Make sure the print spooler service is running
      win_service:
        name: spooler
        state: started
      tags:
        - mytag

    - name: On windows hosts, make sure the telnet client is installed
      win_feature:
        name: telnet-client
      when: ansible_os_family == 'Windows'
      register: telnet_client

    - name: Print some stuff
      debug:
        msg: "Telnet client was installed"
      when: telnet_client.changed

    - name: Print some other stuff
      debug:
        msg: "Telnet client was already present"
      when: telnet_client.changed == False
